services:
    loconox_entity_routing.slug.service.manager:
        class: Loconox\EntityRoutingBundle\Slug\SlugServiceManager

    loconox_entity_routing.host.service.manager:
        class: Loconox\EntityRoutingBundle\Host\HostServiceManager