services:
    loconox_entity_routing.validator.unique_slug:
        class: Loconox\EntityRoutingBundle\Validator\Constraints\UniqueSlugValidator
        arguments: [ "@loconox_entity_routing.slug.service.manager", "@loconox_entity_routing.manager.slug" ]
        tags:
            - { name: validator.constraint_validator, alias: loconox_entity_routing.validator.unique_slug }